dist: xenial  # Required for Python >= 3.7

language: python

# Note: the -python flag in the matrix has no influence, as we use miniconda to
# install Python, which uses the env-variable PYTHON. Having it here is just
# bookkeeping, so it prints the same version in the Travis info.
matrix:
  include:
    - python: 3.7  # => 3.7 no JIT; scooby
      env: PYTHON=3.7 NUMBA_DISABLE_JIT=1 INST="scooby"
    - python: 3.7  # => 3.8 no JIT; no scooby (will become 3.8 soon).
      env: PYTHON=3.7 NUMBA_DISABLE_JIT=1 INST=""
    - python: 3.7  # => 3.7
      env: PYTHON=3.7 INST=""

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --all
  # Useful for debugging any issues with conda
  - conda info -a

  # Install and activate environment, install packages
  - conda create -q -n tenv python=$PYTHON numpy scipy pytest pytest-cov numba
  - source activate tenv
  - pip install coveralls pytest-flake8 $INST
  - python setup.py install


script: pytest --cov=emg3d --flake8

after_success:
  - |
    if [ $NUMBA_DISABLE_JIT == "1" ]; then
      coveralls
    fi
